# Generated by Django 5.2.8 on 2025-12-10 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMaster', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite_Events',
            new_name='Favorites',
        ),
    ]
