# Generated by Django 5.2.8 on 2025-12-10 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMaster', '0002_rename_favorite_events_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='event_address',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='event_city',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='event_state',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='event_tickets',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='event_time',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='event_venue',
        ),
    ]
