# Generated by Django 5.2.8 on 2025-12-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMaster', '0003_remove_favorites_event_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='event_id',
        ),
        migrations.AddField(
            model_name='favorites',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
