# Generated by Django 5.2.8 on 2025-12-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMaster', '0005_event_delete_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
