# Generated by Django 5.2.8 on 2025-12-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMaster', '0006_event_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='', max_length=100),
        ),
    ]
