# Generated by Django 5.2.8 on 2025-12-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMaster', '0008_event_city_event_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
