# Generated by Django 5.2.8 on 2025-12-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMaster', '0009_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
